model:
  hidden_channels: 256
  out_channels:    256
  num_blocks:      4
  num_spherical:   7
  num_radial:      6
  cutoff:          5.0
  fusion:          cat   # options: "cat" or "diff-prod"
  dropout:         0.1

training:
  seed:           42
  batch_size:     16
  epochs:         200
  lr:             1e-4
  weight_decay:   1e-5
  scheduler:
    name:        CosineRestartsDecay
    T_0:         20
    T_mult:      2
    eta_min:     1e-4
    decay:       0.3

data:
  root:            data/equi_dataset
  sdf_folder:      /home/calvin.p/Code/Data/sdf_data
  target_csv:      /home/calvin/Code/Data/target_data/target_data_sin_cos.csv
  input_type:     ['r1h', 'r2h']
  target_columns:  ['psi_1_dihedral_sin', 'psi_1_dihedral_cos']
  keep_hs:         true
  sanitize:        false
  force_reload:    true

logging:
  output_root:    experiments
