_wandb:
    value:
        cli_version: 0.19.11
        code_path: code/dimenet_manual.py
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 9
                - 41
                - 55
                - 77
                - 103
            "2":
                - 1
                - 9
                - 41
                - 55
                - 77
                - 103
            "3":
                - 1
                - 16
                - 23
                - 55
                - 62
            "4": 3.10.16
            "5": 0.19.11
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
data:
    value:
        force_reload: true
        input_types:
            - r1h
            - r2h
        keep_hs: true
        root: data/equi_dataset
        sanitize: false
        sdf_folder: /home/calvin/code/chemprop_phd_customised/habnet/data/processed/sdf_data
        target_columns:
            - psi_1_dihedral_sin
            - psi_1_dihedral_cos
        target_csv: /home/calvin/code/chemprop_phd_customised/habnet/data/processed/target_data/target_data_sin_cos.csv
logging:
    value:
        output_root: experiments
model:
    value:
        cutoff: 5
        dropout: 0.1
        fusion: cat
        hidden_channels: 256
        num_blocks: 4
        num_radial: 6
        num_spherical: 7
        out_channels: 256
training:
    value:
        batch_size: 32
        epochs: 200
        lr: "1e-4"
        scheduler:
            T_0: 20
            T_mult: 2
            decay: 0.3
            eta_min: "1e-4"
            name: CosineRestartsDecay
        seed: 42
        weight_decay: "1e-5"
